.TH lavue 1 "2017-05-12" lavue
.SH NAME
.B lavue
\- Lightweight Live Viewer

.SH SYNOPSIS
.B  lavue
[
.I OPTIONS
]

.SH DESCRIPTION
.B lavue
is a simple implementation of a live viewer front end. It is supposed to show a live image view from xray-detectors at PETRA3.


.SH OPTIONS
.\".IP "--version"
.\"show program's version number and exit
.IP "--help, -h"
show a help message and exit
.IP "--version, -v"
lavue version
.IP "-m MODE, --mode MODE"
interface mode, i.e. user, expert
.IP "-y STYLE, --style STYLE"
QT style
.IP "-e STYLESHEET, --stylesheet STYLESHEET"
QT style sheet
.IP "-j INSTANCE, --instance INSTANCE"
LaVue instance
.IP "-f IMAGEFILE, --image-file IMAGEFILE"
image file name to show
.IP "-s SOURCE, --source SOURCE"
image source, i.e. hidra, http, tangoattr, tangofile, zmq, nxsfile, test
multiple-source names can be separated by semicolon ';'
.IP "-c CONFIGURATION, --configuration CONFIGURATION"
configuration strings for the image source separated by comma, e.g.
  hidra -> '-c haspilatus300k.desy.de'
  http -> '-c haso228eiger/1.5.0'
  tangoattr -> '-c sys/tg_test/1/double_image_ro'
  tangofile -> '-c p00/plt/1/LastImageTaken,p00/plt/1/LastImagePath'
  zmq -> '-c haso228:5535,topic'
  doocsprop -> '-c TTF2.FEL/BLFW2.CAM/BL0M1.CAM/IMAGE_EXT'
  nxsfile -> '-c /tmp/myfile.nxs://entry/data/pilatus'
configuration for multiple-source names can be separated by semicolon ';
.IP "--offset OFFSET"
relative x,y offset for multiple-sources to the first sourceseparated by semicolon ';'
  e.g.
      ;200,300;,54;121,3
      200,300;100,
.IP "-w RANGEWINDOW, --range-window RANGEWINDOW"
range window slices, i.e. x1:x2,y1:y2 , e.g. -w 10:500,20:200
  where 'm' is '-'
.IP "--ds-factor DSFACTOR"
integer down-sampling factor
.IP "--ds-reduction DSREDUCTION"
down-sampling reduction function, i.e. 'max', 'min', 'mean' or 'sum'
.IP "-z, --filters"
apply image filters
.IP "-o MBUFFER, --memory-buffer MBUFFER"
size of memory buffer in frames
.IP "--channel CHANNEL"
default channel number or 'sum', 'mean', 'rgb' or RGB channels separated by comma e.g.'0,1,3'
.IP "-b BKGFILE, --bkg-file BKGFILE"
background file-name to load
.IP "-k MASKFILE, --mask-file MASKFILE"
mask file-name to load
.IP "-p MASKHIGHVALUE, --mask-high-value MASKHIGHVALUE"
highest pixel value to show
.IP "-t TRANSFORMATION, --transformation TRANSFORMATION"
image transformation, i.e.
flip-up-down, flip-left-right, transpose,
rot90, rot180, rot270, rot180+transpose
.IP "-i SCALING, --scaling SCALING"
intensity scaling, i.e. sqrt, linear, log
.IP "-l LEVELS, --levels LEVELS"
intensity display levels e.g. -l m20,20
where 'm' is '-'
.IP "-q AUTOFACTOR, --factor AUTOFACTOR"
factor of the highest pick for automatic levels in %, e.g. -q 0.5
.IP "-g GRADIENT, --gradient GRADIENT"
color gradient, i.e.
grey, highcontrast, thermal, flame, bipolar, spectrum, spectrumclip, greyclip, reversegrey, cyclic, yellowy, inverted
.IP "-r VIEWRANGE, --range VIEWRANGE"
viewbox range, i.e. xmin,ymin,xsize,ysize , e.g. -l 5.6,m60.7,543.2,444.11
.IP "-x, --start"
connect the image source
.IP "-u TOOL, --tool TOOL"
utility tool, i.e. intensity, roi, movemotors, meshscan, linecut, projections, 1d-plot, angle/q, q+roi+proj
.IP "-a TANGODEVICE, --tango-device TANGODEVICE"
tango device to communicated with clients during the run
.IP "-d DOORDEVICE, --door DOORDEVICE"
door device to communicated with sardana during the run
.IP "-n ANALYSISDEVICE, --analysis-device ANALYSISDEVICE"
tango analysis device of LambdaOnlineAnalysis to communicate with analysis clients during the run
.IP "--log LOG"
logging level, i.e. debug, info, warning, error, critical


.SH SEE ALSO
https://github.com/syncope/lavue/
https://github.com/jkotan/lavue/

.SH COPYRIGHT
Copyrights (c) 2017, GNU GPL v2, DESY, Christoph Rosemann, Jan Kotanski, Andre Rothkirch

.SH BUGS
Please report bugs on the project's mailing list:
mailto://jankotan@gmail.com

.SH AUTHORS
Christoph Rosemann <christoph.rosemann@desy.de>, Jan Kotanski <jankotan@gmail.com>, Andre Rothkirch <andre.rothkirch@desy.de>
