.TH LavueController 1 "2018-01-02" LavueController
.SH NAME
.B LavueController
\- Tango Device controlling lavue parameters

.SH SYNOPSIS
.B  LavueController
.I <instance_name>
[-v[trace level]] [-file=<file_name> | -nodb [-dlist <device name list>] ]
] 


.SH DESCRIPTION
.B LavueController
is a Tango server which allows to send parameters to the live image viewer
lavue during its operation. The possible parameters correspond
to tango attrbutes of the device.


.SH OPTIONS
.\".IP "--version"
.\"show program's version number and exit
.IP "-v"
trace level
.IP "-file"
file name
.IP "-nodb"
without DB
.IP "-dlist"
device name list        

.SH SEE ALSO
https://github.com/lavue-org/lavue/

.SH COPYRIGHT
Copyrights (c) 2018, GNU GPL v2, DESY, Jan Kotanski

.SH BUGS
Please report bugs on the project's mailing list:
mailto://jankotan@gmail.com

.SH AUTHORS
Jan Kotanski <jankotan@gmail.com> 

