#!/usr/bin/env bash

export LAVUE_HIDE_VERSIONS=TRUE
rm -rf build/sphinx/html/
mkdir -p /home/jkotan/ndts/lavue/doc/_static
python3 setup.py build_sphinx
unset LAVUE_HIDE_VERSIONS

cp -r build/sphinx/html/* lavuelib/help
rm lavuelib/help/objects.inv


# python3 setup.py build --executable '/usr/bin/env python3'
# python3 setup.py sdist
# python3 setup.py bdist_wheel
