all:
	g++ -std=c++11 -owriter2d writer2d.cpp -I/usr/include/hdf5/serial -I/usr/include /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so  /usr/lib/x86_64-linux-gnu/libboost_program_options.so -lhdf5 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /usr/lib/x86_64-linux-gnu/libboost_system.so /usr/lib/x86_64-linux-gnu/libboost_regex.so /usr/lib/x86_64-linux-gnu/libboost_date_time.so -lboost_system   -lh5cpp -lz -ldl -lm -L/usr/lib/x86_64-linux-gnu/hdf5/serial





